//Exercise 23
var flower = 'Rose';
console.log("Is flower == 'Rose'? I predict True.");
console.log(flower === 'Rose');
console.log("Is flower != 'Jasmine'? I predict True.");
console.log(flower !== 'Jasmine');
console.log("Is flower == 'Lily'? I predict False.");
console.log(flower === 'Lily');
console.log("Is flower != 'Daisy'? I predict False.");
console.log(flower === 'Daisy');
console.log("Is flower != 'Peony'? I predict True.");
console.log(flower !== 'Peony');
console.log("Is flower != 'Tulip'? I predict True.");
console.log(flower !== 'Tulip');
console.log("Is flower != 'Sun Flower'? I predict True.");
console.log(flower !== 'Sun Flower');
console.log("Is flower != 'Orchid'? I predict False.");
console.log(flower === 'Orchid');
console.log("Is flower != 'Daffodil'? I predict False.");
console.log(flower === 'Daffodil');
